export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const GET_POPULAR_MOVIES_SUCCES = "GET_POPULAR_MOVIES_SUCCES";
export const GET_POPULAR_MOVIES_ERROR = "GET_POPULAR_MOVIES_ERROR";

export const GET_FILTER_MOVIES = "GET_FILTER_MOVIES";
export const GET_FILTER_MOVIES_SUCCES = "GET_FILTER_MOVIES_SUCCES";
export const GET_FILTER_MOVIES_ERROR = "GET_FILTER_MOVIES_ERROR";

export const GET_CURRENT_MOVIE = "GET_CURRENT_MOVIE";
export const GET_CURRENT_MOVIE_SUCCES = "GET_CURRENT_MOVIE_SUCCES";
export const GET_CURRENT_MOVIE_ERROR = "GET_CURRENT_MOVIE_ERROR";

export const SET_SEARCH_MOVIE = "SET_SEARCH_MOVIE";
